//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adtransfer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<BrandManager> BrandManagers { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Channel> Channels { get; set; }
        public virtual DbSet<Distribution> Distributions { get; set; }
        public virtual DbSet<System_User> System_User { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
    }
}
