//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adtransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandManager
    {
        public int BrandManagerID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PINCode { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string State { get; set; }
        public string Password { get; set; }
        public int ClientID { get; set; }
        public Nullable<int> type { get; set; }
        public bool Status { get; set; }
    }
}
