//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adtransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public int ChannelID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public string Logo { get; set; }
        public string FtpHost { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<int> ChannelLoginID { get; set; }
        public string ChannelLoginName { get; set; }
        public string ChannelLoginAddress { get; set; }
        public string ChannelLoginCity { get; set; }
        public string ChannelLoginCountry { get; set; }
        public string ChannelLoginPinCode { get; set; }
        public string ChannelLoginEmail { get; set; }
        public string ChannelLoginPhone { get; set; }
        public string ChannelLoginState { get; set; }
        public string ChannelLoginPassword { get; set; }
    }
}
