//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adtransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribution
    {
        public int DistributionID { get; set; }
        public string Caption { get; set; }
        public string Keyid { get; set; }
        public string Duration { get; set; }
        public string Language { get; set; }
        public string Client { get; set; }
        public string Agency { get; set; }
        public string Brand { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
